language: c

git:
  depth: 1

install:
  - curl -o /tmp/mdbook.tar.gz
        -L 'https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.7/mdbook-v0.1.7-x86_64-unknown-linux-gnu.tar.gz'
    && tar xf /tmp/mdbook.tar.gz -C ~/bin

script:
  - mdbook build

before_deploy:
  - zip -r too-many-lists.zip book

deploy:
  provider: releases
  api_key: "$GH_DEPLOY_TOKEN"
  file: "too-many-lists.zip"
  skip_cleanup: true
  on:
    tags: true
