language: rust
rust:
  - stable

git:
  depth: 1

# Missed cache and too slow
# Use pre-build binary instead
#cache: cargo
before_script:
  #- (cargo install mdbook --vers 0.1.7 --force || true)
  - curl -o /tmp/mdbook.tar.gz
        -L 'https://github.com/rust-lang-nursery/mdBook/releases/download/v0.1.7/mdbook-v0.1.7-x86_64-unknown-linux-gnu.tar.gz'
    && tar xf /tmp/mdbook.tar.gz -C ~/.cargo/bin

script:
  - mdbook build

after_success:
  - zip -r too-many-lists.zip book

deploy:
  provider: releases
  api_key: "$GH_DEPLOY_TOKEN"
  file: "too-many-lists.zip"
  skip_cleanup: true
  on:
    tags: true
