language: c

git:
  depth: 1
  quiet: true

install:
  - |
    curl \
      -sSL \
      'https://github.com/rust-lang/mdBook/releases/download/v0.3.5/mdbook-v0.3.5-x86_64-unknown-linux-gnu.tar.gz' \
    | tar -xzf - -C "$HOME/bin"
  - export PATH="$PATH:$HOME/bin"

script:
  - mdbook build

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: book
  github-token: $GH_DEPLOY_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
